name: awesimsoss
channels:
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - astropy=4.0
  - healpy=1.11.0
  - tqdm=4.36.1
  - bokeh=1.3.4
  - click=7.0
  - ipython=7.12.0
  - jupyter=1.0.0
  - numpy=1.18.1
  - pytest=5.4.3
  - python=3.6.8
  - scipy=1.2.1
  - asdf=2.3.3
  - crds=7.3.3
  - webbpsf-data=0.8.0
  - pip:
    - asteval==0.9.14
    - astroquery=0.4.1
    - awesimsoss==0.3.1
    - batman-package==2.4.6
    - bibtexparser==1.2.0
    - dustmaps==1.0.4
    - hotsoss==0.1.7
    - gitfit==0.1.1
    - jwst==0.13.8a0.dev37+g1f2237de
    - jwst-backgrounds==1.1.1
    - lmfit==0.9.13
    - numpydoc==0.8.0
    - poppy==0.7.0
    - progressbar2==3.42.0
    - sedkit==0.3.1
    - svo-filters==0.2.19
    - webbpsf==0.8.0
    - werkzeug==0.16.1
